language: php
php: '8.0'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist --no-interaction

stages:
  - name: test
  - name: codecov

jobs:
  include:
    - stage: test
      if: type = pull_request
      script:
        - phpunit
    - stage: codecov
      if: branch = main
      script:
        - curl -Os https://uploader.codecov.io/latest/linux/codecov
        - chmod +x codecov
        - ./codecov
