language: php
php:
  - '8.0'
  - '8.1'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist --no-interaction

stages:
  - name: testing
  script:
    - phpunit

  - name: codecov upload
  script:
    - curl -Os https://uploader.codecov.io/latest/linux/codecov
    - chmod +x codecov
    - ./codecov
