language: php
php:
  - '8.0'
  - '8.1'

cache:
  directories:
    - $HOME/.composer/cache

env:
  - XDEBUG_MODE=coverage

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - phpunit
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov
