language: php
php: '8.0'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist --no-interaction

stages:
  - name: test
    if: type = pull_request or (branch = main and type = push)
  - name: codecov
    if: branch = main and type = push

jobs:
  include:
    - stage: test
      script:
        - phpunit
    - stage: codecov
      script:
        - curl -Os https://uploader.codecov.io/latest/linux/codecov
        - chmod +x codecov
        - ./codecov
