language: php
php:
  - '8.0'
  - '8.1'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist --no-interaction

stages:
  - name: test
    if: type = pull_request
  - name: codecov
    if: head_branch = main

jobs:
  include:
    - stage: test
      script:
        - phpunit
    - stage: codecov
      php: '8.0'
      script:
        - curl -Os https://uploader.codecov.io/latest/linux/codecov
        - chmod +x codecov
        - ./codecov
