language: php
php: '8.0'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist --no-interaction

stages:
  - name: test

  - name: codecov
    if: branch = main

jobs:
  include:
    - name: "Testing"
      php:
        - '8.0'
        - '8.1'
      if: type = pull_request
      script:
        - phpunit
    - name: "Uploading to Codecov"
      php: '8.0'
      script:
        - curl -Os https://uploader.codecov.io/latest/linux/codecov
        - chmod +x codecov
        - ./codecov
