language: php
php:
  - '8.0'
  - '8.1'

branches:
  only:
    - master
    - main

cache:
  directories:
    - $HOME/.composer/cache

env:
  - XDEBUG_MODE=coverage

before_script:
  - composer install --prefer-dist --no-interaction

script:
  - phpunit
