language: php
php:
  - '8.0'
  - '8.1'

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist --no-interaction

jobs:
  include:
    - stage: testing
    script:
      - phpunit

    - stage: codecov upload
    if: branch = master
    script:
      - curl -Os https://uploader.codecov.io/latest/linux/codecov
      - chmod +x codecov
      - ./codecov
